---
title: "Data Submission Guidelines"
---

All data sets must have the following accompanying documents to ensure that others can understand the data. Please submit datasets as a 'package' with the following additional files.

**Note:** Trawl catch/specimen data, CTD, and Rosette data must be transformed to the standardized [IYS Data Template](https://docs.google.com/spreadsheets/d/1bRWwUktLyE9LrqAkqRWp57k0OXtlVLa7/edit?usp=sharing&ouid=115784895965147788100&rtpof=true&sd=true) and submitted with all required accompanying files noted below. All other datasets may be submitted in a non-standardized wide view of the data (every variable has it's own column), so long as it is possible to link this data with events from the trawl catch/specimen or rosette data tables using a common column such as an eventID or a combimation of station name and time.

Required accompanying files:

* **Supply data as plain text files:** (eg .csv, .txt) or common formats such as Microsoft Excel (.xlsx). Avoid formats that require special software. 
  - Indicate the time zone of date and time columns (UTC is preferred)
  - Report locations as latitude and longitude in decimal degrees (ie. 49.12345, 110.54321)

* **Data Dictionary:** Define each variable (column name) in every table of your data. Include variable name, units, and short description if needed. Note that for Trawl catch/specimen data, CTD data, and Rosette the Data Dictionary exists as a tab in the Template Spreadsheet File. 

* **README file** (.txt or .docx) with the following sections:

  - **Statement of Data Access:** When can data submitted be made public? Can all of the submitted data be published, or can only a summarized/aggregated view be published?

  - **Abstract:** This information will appear as the summary text in the metadata catalogue. Focus on **what** variables were measured, **how** the variables were measured, and **why** the data were collected to inform your hypotheses.

  - **Protocols**: Describe thoroughly the field, lab, and data processing protocols used to produce your data. This could be the same text used in a Cruise Report if there is sufficient information to reproduce methods.
  
* **Supplementary Materials** Provide publication(s) referenced in protocol description. Provide any scripts or calibration files that were used to clean up/quality control data, filter data from the raw data, or calculate values in the final data package.


Email data packages to iys.data@hakai.org
