---
title: "Published Data"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE)
library(ckanr)
library(tidyverse)
```

```{r, include = FALSE}
ckanr_setup(url = "http://iys.hakai.org", key = "d386ae49-3756-4c39-945f-1b428b0fc130")
pkgs <- package_list_current(as = "table", limit = 2000)

names(pkgs)

subset <- pkgs %>% 
  select(title, id, `metadata-point-of-contact`, `unique-resource-identifier-full`) %>% 
  filter(`unique-resource-identifier-full` != "NULL") 

# rp <- pkgs$`cited-responsible-party`
 
names <- bind_rows(subset$`metadata-point-of-contact`) %>% 
  select(`Contact Person` = 'individual-name',
         `Contact email` = 'contact-info_email')

dois <- bind_rows(subset$`unique-resource-identifier-full`) %>% 
  mutate(dois = paste0("https://doi.org/", code)) %>% 
  select(`Digital Object Identifier`= dois)

subset <- tibble(`Dataset Title` = subset$title, names, dois)
```

```{r, include = TRUE}
knitr::kable(subset, caption = "IYS datasets that have been published")
```

```{r}
# library(robis)
# 
# trawl_20 <- occurrence(datasetid = "bdbfda38-c0fd-483c-85eb-4202baff1e52", mof = TRUE)
```
